/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bd.Conexion;
import bd.Data;
import static com.sun.corba.se.impl.util.Utility.printStackTrace;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.*;

/**
 *
 * @author Emilio
 */
public class AppCA extends javax.swing.JFrame {
    private Data d;

    /**
     * Creates new form AppCA
     */
    public AppCA() {
        initComponents();
        try {
            d=new Data();
            iniciar();
            setLocationRelativeTo(null);
        } catch (SQLException ex) {
            System.out.println("Error de conexion"+ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabDT = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDT_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDT_Apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spDT_Edad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbDT_Club = new javax.swing.JComboBox<>();
        spDT_Anos = new javax.swing.JSpinner();
        txtDT_Sueldo = new javax.swing.JTextField();
        txtDT_Nombre = new javax.swing.JTextField();
        cbDT_Nacionalidad = new javax.swing.JComboBox<>();
        btnCrearDT = new javax.swing.JButton();
        btnActualizarDT = new javax.swing.JButton();
        btnCancelarDT = new javax.swing.JButton();
        btnEliminarDT = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabDT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabDTMouseReleased(evt);
            }
        });
        tabDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabDTKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabDT);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setText("ID");

        txtDT_ID.setEditable(false);

        jLabel2.setText("Nombre");

        txtDT_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDT_ApellidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido");

        jLabel4.setText("Edad");

        jLabel5.setText("Nacionalidad");

        jLabel6.setText("Club Deportivo");

        jLabel7.setText("Años como DT");

        jLabel8.setText("Sueldo Fifa");

        cbDT_Club.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDT_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDT_NombreActionPerformed(evt);
            }
        });

        cbDT_Nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCrearDT.setText("Crear");
        btnCrearDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDTActionPerformed(evt);
            }
        });

        btnActualizarDT.setText("Actualizar");
        btnActualizarDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDTActionPerformed(evt);
            }
        });

        btnCancelarDT.setText("Cancelar");
        btnCancelarDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDTActionPerformed(evt);
            }
        });

        btnEliminarDT.setText("Eliminar");
        btnEliminarDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spDT_Anos)
                            .addComponent(cbDT_Club, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(28, 28, 28)
                                .addComponent(txtDT_Sueldo))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDT_Apellido)
                                    .addComponent(cbDT_Nacionalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spDT_Edad))))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtDT_Nombre)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelarDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDT_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(spDT_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbDT_Nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbDT_Club, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spDT_Anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDT_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearDT)
                    .addComponent(btnActualizarDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarDT)
                    .addComponent(btnEliminarDT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Director Tecnico", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Partidos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDT_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDT_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDT_ApellidoActionPerformed

    private void txtDT_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDT_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDT_NombreActionPerformed

    private void tabDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabDTKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabDTKeyReleased

    private void tabDTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDTMouseReleased
        if(evt.getClickCount()==1){
            try {
                int fila=tabDT.getSelectedRow();
                int id=(int)tabDT.getValueAt(fila, 0);
                DT dt=d.getDT(id);
                
                txtDT_ID.setText(Integer.toString(dt.getId()));
                txtDT_Nombre.setText(dt.getNombre());
                txtDT_Apellido.setText(dt.getApellido());
                txtDT_Sueldo.setText(Integer.toString(dt.getSueldoFifa()));
                
                ClubDeportivo c=d.getClubDeportivo(dt.getClubDeportivo());
                int indiceCbo=cbDT_Club.getItemCount();                
                for(int i=0; i<indiceCbo; i++){
                    String nombreObj=cbDT_Club.getItemAt(i).toString();
                    if(nombreObj.equalsIgnoreCase(c.getNombre())){
                        cbDT_Club.setSelectedIndex(i);
                    }
                }
                
                Nacionalidad n=d.getNacionalidad(dt.getNacionalidad());
                int indiceCbo2=cbDT_Nacionalidad.getItemCount();
                for(int i=0; i<indiceCbo2; i++){
                    String nombreObj2=cbDT_Nacionalidad.getItemAt(i).toString();
                    if(nombreObj2.equalsIgnoreCase(n.getPais())){
                        cbDT_Nacionalidad.setSelectedIndex(i);
                    }
                }
                
                spDT_Anos.setValue(dt.getAniosDT());
                spDT_Edad.setValue(dt.getEdad());
                
                btnCrearDT.setEnabled(false);
                btnEliminarDT.setEnabled(true);
                btnCancelarDT.setEnabled(true);
                btnActualizarDT.setEnabled(true);
            } catch (SQLException e) {
                
            }
        }        
    }//GEN-LAST:event_tabDTMouseReleased

    private void btnCrearDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDTActionPerformed
        DT nuevoDT=new DT();
        nuevoDT.setNombre(txtDT_Nombre.getText());
        nuevoDT.setApellido(txtDT_Apellido.getText());
        nuevoDT.setEdad(Integer.parseInt(spDT_Edad.getValue().toString()));
        nuevoDT.setAniosDT(Integer.parseInt(spDT_Anos.getValue().toString()));
        nuevoDT.setSueldoFifa(Integer.parseInt(txtDT_Sueldo.getText()));
        
        ClubDeportivo club=(ClubDeportivo)cbDT_Club.getSelectedItem();
        nuevoDT.setClubDeportivo(club.getId());
        
        Nacionalidad pais=(Nacionalidad)cbDT_Nacionalidad.getSelectedItem();
        nuevoDT.setNacionalidad(pais.getId());
        
        try {
            d.crearDT(nuevoDT);
            JOptionPane.showMessageDialog(this, "DT Creado");
            btnCancelarDT.doClick();
            cargarTablaDT();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "No se ha podido crear DT: "+ex.getMessage());
        } catch (NumberFormatException exx){
            JOptionPane.showMessageDialog(this, "Existen datos invalidos");
        }
        
    }//GEN-LAST:event_btnCrearDTActionPerformed

    private void btnCancelarDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDTActionPerformed
        txtDT_Nombre.setText(null);
        txtDT_Apellido.setText(null);
        txtDT_ID.setText(null);
        txtDT_Sueldo.setText(null);
        spDT_Anos.setValue(0);
        spDT_Edad.setValue(0);
        cbDT_Club.setSelectedIndex(0);
        cbDT_Nacionalidad.setSelectedIndex(0);
        tabDT.clearSelection();        
        btnActualizarDT.setEnabled(false);
        btnCancelarDT.setEnabled(false);
        btnCrearDT.setEnabled(true);
        btnEliminarDT.setEnabled(false);        
    }//GEN-LAST:event_btnCancelarDTActionPerformed

    private void btnActualizarDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDTActionPerformed
        try {
            int id=Integer.parseInt(txtDT_ID.getText());
            String nombre=txtDT_Nombre.getText();
            String apellido=txtDT_Apellido.getText();
            int sueldo=Integer.parseInt(txtDT_Sueldo.getText());
            int edad=Integer.parseInt(spDT_Edad.getValue().toString());
            int anosDT=Integer.parseInt(spDT_Anos.getValue().toString());
            
            ClubDeportivo club=(ClubDeportivo)cbDT_Club.getSelectedItem();
            int idClub=club.getId();
            Nacionalidad pais=(Nacionalidad)cbDT_Nacionalidad.getSelectedItem();
            int idNacion=pais.getId();
            
            DT dt=new DT(id, nombre, apellido, edad, idNacion, idClub, anosDT, sueldo);
            d.actualizarDT(dt);
            cargarTablaDT();
            btnCancelarDT.doClick();
            
            JOptionPane.showMessageDialog(this, "Se ha actualizado DT");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error para actualizar DT: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarDTActionPerformed

    private void btnEliminarDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDTActionPerformed
        try {
            int id=Integer.parseInt(txtDT_ID.getText());
            d.eliminarDT(id);
            cargarTablaDT();
            btnCancelarDT.doClick();
            
            JOptionPane.showMessageDialog(this,"Se ha eliminado DT");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar DT: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarDTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        String nombre=UIManager.getSystemLookAndFeelClassName();
        try {
            UIManager.setLookAndFeel(nombre);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDT;
    private javax.swing.JButton btnCancelarDT;
    private javax.swing.JButton btnCrearDT;
    private javax.swing.JButton btnEliminarDT;
    private javax.swing.JComboBox<Object> cbDT_Club;
    private javax.swing.JComboBox<Object> cbDT_Nacionalidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spDT_Anos;
    private javax.swing.JSpinner spDT_Edad;
    private javax.swing.JTable tabDT;
    private javax.swing.JTextField txtDT_Apellido;
    private javax.swing.JTextField txtDT_ID;
    private javax.swing.JTextField txtDT_Nombre;
    private javax.swing.JTextField txtDT_Sueldo;
    // End of variables declaration//GEN-END:variables

    private void iniciar() throws SQLException {
        cargarTablaDT();
        actualizarCBONacionalidad();
        actualizarCBOClubDeportivo();
        btnCancelarDT.doClick();
//        cargarTablaPartidos();
    }

    private void cargarTablaPartidos() throws SQLException{
//        TMPartido modeloPartidos=new TMPartido(d.getPartidos());
//        tbl_Partidos.setModel(modeloPartidos);
    }

    private void cargarTablaDT() throws SQLException{
        TM_DT model=new TM_DT(d.getDTs());
        tabDT.setModel(model);
        tabDT.getColumnModel().getColumn(0).setPreferredWidth(5);
        tabDT.getColumnModel().getColumn(1).setPreferredWidth(10);
        tabDT.getColumnModel().getColumn(2).setPreferredWidth(10);
    }

    private void actualizarCBONacionalidad() {
        try {
            List<Nacionalidad> paises=d.getNacionalidades();
            cbDT_Nacionalidad.removeAllItems();
            
            for(Nacionalidad n: paises){
                cbDT_Nacionalidad.addItem(n);
            }
        } catch (Exception e) {
            System.out.println("Error cargar cbGenero: "+e.getMessage());
        }
    }

    private void actualizarCBOClubDeportivo() {
        try {
            List<ClubDeportivo> clubes=d.getClubDeportivos();
            cbDT_Club.removeAllItems();
            
            for(ClubDeportivo club: clubes){
                cbDT_Club.addItem(club);
            }
        } catch (Exception e) {
            System.out.println("Error cargar cbDT_Club: "+e.getMessage());
        }        
    }

    private void CrudActualizar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
