/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bd.Conexion;
import bd.Data;
import static com.sun.corba.se.impl.util.Utility.printStackTrace;
import com.sun.javafx.image.impl.IntArgb;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.*;

/**
 *
 * @author Emilio
 */
public class AppCA extends javax.swing.JFrame {
    private Data d;

    /**
     * Creates new form AppCA
     */
    public AppCA() {
        initComponents();
        try {
            d=new Data();
            iniciar();
            setLocationRelativeTo(null);
        } catch (SQLException ex) {
            System.out.println("Error de conexion: "+ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabPartidos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPartido_ID = new javax.swing.JTextField();
        btnPartido_Crear = new javax.swing.JButton();
        btnPartidoActualizar = new javax.swing.JButton();
        btnPartidoCancelar = new javax.swing.JButton();
        btnPartidoEliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cboPartido_SeleccionA = new javax.swing.JComboBox<>();
        cboPartido_SeleccionB = new javax.swing.JComboBox<>();
        cboPartido_ArbitroA = new javax.swing.JComboBox<>();
        cboPartido_ArbitroLA = new javax.swing.JComboBox<>();
        cboPartido_ArbitroLB = new javax.swing.JComboBox<>();
        cboPartido_ArbitroD = new javax.swing.JComboBox<>();
        cboPartido_Estadio = new javax.swing.JComboBox<>();
        spPartido_Publico = new javax.swing.JSpinner();
        spPartido_TerminoHora = new javax.swing.JSpinner();
        spPartido_TerminoMinuto = new javax.swing.JSpinner();
        spPartido_InicioHora = new javax.swing.JSpinner();
        spPartido_InicioMinuto = new javax.swing.JSpinner();
        spPartido_Dia = new javax.swing.JSpinner();
        spPartido_Mes = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        cboPartido_Fase = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txtPartidoBusqueda = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabDT = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDT_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDT_Apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spDT_Edad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbDT_Club = new javax.swing.JComboBox<>();
        spDT_Anos = new javax.swing.JSpinner();
        txtDT_Sueldo = new javax.swing.JTextField();
        txtDT_Nombre = new javax.swing.JTextField();
        cbDT_Nacionalidad = new javax.swing.JComboBox<>();
        btnCrearDT = new javax.swing.JButton();
        btnActualizarDT = new javax.swing.JButton();
        btnCancelarDT = new javax.swing.JButton();
        btnEliminarDT = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtBuscarJugador = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtIDJugador = new javax.swing.JTextField();
        txtNombreJugador = new javax.swing.JTextField();
        txtApellidoJugador = new javax.swing.JTextField();
        spEdadJugador = new javax.swing.JSpinner();
        spDebutJugador = new javax.swing.JSpinner();
        spSueldoJugador = new javax.swing.JSpinner();
        spGolesJugador = new javax.swing.JSpinner();
        spAtajadasJugador = new javax.swing.JSpinner();
        spTarjetasAmarillas = new javax.swing.JSpinner();
        spTarjetasRojas = new javax.swing.JSpinner();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cboClubDeportivoJugador = new javax.swing.JComboBox<>();
        cboEstadoFisicoJugador = new javax.swing.JComboBox<>();
        cboNacionalidadJugador = new javax.swing.JComboBox<>();
        cboPosicionJugador = new javax.swing.JComboBox<>();
        chkHabilitado = new javax.swing.JCheckBox();
        chkTitular = new javax.swing.JCheckBox();
        btnCrearJugador = new javax.swing.JButton();
        btnActualizarJugador = new javax.swing.JButton();
        btnCancelarJugador = new javax.swing.JButton();
        btnEliminarJugador = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabJugador = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabPartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabPartidosMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabPartidos);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel10.setText("ID");

        txtPartido_ID.setEditable(false);

        btnPartido_Crear.setText("Crear");
        btnPartido_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartido_CrearActionPerformed(evt);
            }
        });

        btnPartidoActualizar.setText("Actualizar");
        btnPartidoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidoActualizarActionPerformed(evt);
            }
        });

        btnPartidoCancelar.setText("Cancelar");
        btnPartidoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidoCancelarActionPerformed(evt);
            }
        });

        btnPartidoEliminar.setText("Eliminar");
        btnPartidoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidoEliminarActionPerformed(evt);
            }
        });

        jLabel11.setText("Seleccion 1");

        jLabel12.setText("Seleccion 2");

        jLabel13.setText("1er Arbitro");

        jLabel14.setText("Arbitro Lateral 1");

        jLabel15.setText("Arbitro Lateral 2");

        jLabel16.setText("Cuarto Arbitro");

        jLabel17.setText("Estadio");

        jLabel18.setText("Fecha");

        jLabel19.setText("Publico");

        jLabel20.setText("Hora inicio");

        jLabel21.setText("Hora Termino");

        cboPartido_SeleccionA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboPartido_SeleccionB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboPartido_ArbitroA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboPartido_ArbitroLA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboPartido_ArbitroLB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboPartido_ArbitroD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboPartido_Estadio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spPartido_TerminoHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        spPartido_TerminoMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        spPartido_InicioHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        spPartido_InicioMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        spPartido_Dia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        spPartido_Mes.setModel(new javax.swing.SpinnerListModel(new String[] {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"}));

        jLabel23.setText("Fase");

        cboPartido_Fase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPartido_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(btnPartidoCancelar)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboPartido_Estadio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboPartido_Fase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboPartido_SeleccionA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboPartido_SeleccionB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spPartido_Publico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPartido_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(spPartido_InicioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spPartido_InicioMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(spPartido_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spPartido_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cboPartido_ArbitroD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboPartido_ArbitroLB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboPartido_ArbitroLA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboPartido_ArbitroA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(spPartido_TerminoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spPartido_TerminoMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPartidoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPartidoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPartido_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboPartido_SeleccionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPartido_SeleccionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cboPartido_ArbitroA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cboPartido_ArbitroLA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(cboPartido_ArbitroLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cboPartido_ArbitroD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(cboPartido_Estadio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spPartido_Publico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spPartido_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spPartido_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spPartido_InicioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spPartido_InicioMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spPartido_TerminoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spPartido_TerminoMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cboPartido_Fase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnPartido_Crear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPartidoCancelar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnPartidoActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPartidoEliminar)))
                .addGap(26, 26, 26))
        );

        jLabel22.setText("Busqueda");

        txtPartidoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPartidoBusquedaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPartidoBusqueda)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtPartidoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Partidos", jPanel1);

        tabDT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabDTMouseReleased(evt);
            }
        });
        tabDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabDTKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabDT);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setText("ID");

        txtDT_ID.setEditable(false);

        jLabel2.setText("Nombre");

        txtDT_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDT_ApellidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido");

        jLabel4.setText("Edad");

        jLabel5.setText("Nacionalidad");

        jLabel6.setText("Club Deportivo");

        jLabel7.setText("Años como DT");

        jLabel8.setText("Sueldo Fifa");

        cbDT_Club.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDT_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDT_NombreActionPerformed(evt);
            }
        });

        cbDT_Nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCrearDT.setText("Crear");
        btnCrearDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDTActionPerformed(evt);
            }
        });

        btnActualizarDT.setText("Actualizar");
        btnActualizarDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDTActionPerformed(evt);
            }
        });

        btnCancelarDT.setText("Cancelar");
        btnCancelarDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDTActionPerformed(evt);
            }
        });

        btnEliminarDT.setText("Eliminar");
        btnEliminarDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelarDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarDT, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(btnEliminarDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(txtDT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtDT_Nombre))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spDT_Anos)
                            .addComponent(txtDT_Sueldo)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDT_Club, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spDT_Edad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDT_Apellido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbDT_Nacionalidad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDT_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spDT_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbDT_Nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbDT_Club))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spDT_Anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDT_Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearDT)
                    .addComponent(btnActualizarDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarDT)
                    .addComponent(btnEliminarDT))
                .addContainerGap())
        );

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        jLabel9.setText("Busqueda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusqueda)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Director Tecnico", jPanel2);

        jLabel24.setText("Búsqueda:");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel25.setText("ID:");

        jLabel26.setText("Nombre:");

        jLabel27.setText("Apellido:");

        jLabel28.setText("Edad:");

        jLabel29.setText("Debut:");

        jLabel30.setText("Goles:");

        jLabel31.setText("Atajadas:");

        jLabel32.setText("T. Amarillas:");

        jLabel33.setText("T. Rojas:");

        jLabel34.setText("Sueldo:");

        jLabel35.setText("Posición:");

        jLabel36.setText("Nacionalidad:");

        jLabel37.setText("C. Deportivo:");

        jLabel38.setText("Estado Físico:");

        cboClubDeportivoJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboEstadoFisicoJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboNacionalidadJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboPosicionJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPosicionJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPosicionJugadorActionPerformed(evt);
            }
        });

        chkHabilitado.setText("Habilitado");

        chkTitular.setText("Titular");

        btnCrearJugador.setText("Añadir");

        btnActualizarJugador.setText("Modificar");

        btnCancelarJugador.setText("Cancelar");

        btnEliminarJugador.setText("Eliminar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel34))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtApellidoJugador, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spEdadJugador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(spDebutJugador, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIDJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spSueldoJugador)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spGolesJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(spAtajadasJugador)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(chkHabilitado)
                                .addGap(18, 18, 18)
                                .addComponent(chkTitular))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel38))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboPosicionJugador, 0, 104, Short.MAX_VALUE)
                                    .addComponent(spTarjetasAmarillas)
                                    .addComponent(spTarjetasRojas)
                                    .addComponent(cboNacionalidadJugador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboClubDeportivoJugador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboEstadoFisicoJugador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel37)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCrearJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnEliminarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtIDJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtApellidoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(spEdadJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(spDebutJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(spSueldoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(spGolesJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(spAtajadasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(spTarjetasAmarillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(spTarjetasRojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cboPosicionJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cboNacionalidadJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(cboClubDeportivoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cboEstadoFisicoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkTitular)
                    .addComponent(chkHabilitado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearJugador)
                    .addComponent(btnActualizarJugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarJugador)
                    .addComponent(btnEliminarJugador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabJugadorMouseReleased(evt);
            }
        });
        tabJugador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabJugadorKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tabJugador);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarJugador)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtBuscarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Jugadores", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDT_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDT_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDT_ApellidoActionPerformed

    private void txtDT_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDT_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDT_NombreActionPerformed

    private void tabDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabDTKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabDTKeyReleased

    private void tabDTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDTMouseReleased
        if(evt.getClickCount()==1){
            try {
                int fila=tabDT.getSelectedRow();
                int id=(int)tabDT.getValueAt(fila, 0);
                DT dt=d.getDT(id);
                
                txtDT_ID.setText(Integer.toString(dt.getId()));
                txtDT_Nombre.setText(dt.getNombre());
                txtDT_Apellido.setText(dt.getApellido());
                txtDT_Sueldo.setText(Integer.toString(dt.getSueldoFifa()));
                
                ClubDeportivo c=d.getClubDeportivo(dt.getClubDeportivo());
                int indiceCbo=cbDT_Club.getItemCount();                
                for(int i=0; i<indiceCbo; i++){
                    String nombreObj=cbDT_Club.getItemAt(i).toString();
                    if(nombreObj.equalsIgnoreCase(c.getNombre())){
                        cbDT_Club.setSelectedIndex(i);
                    }
                }
                
                Nacionalidad n=d.getNacionalidad(dt.getNacionalidad());
                int indiceCbo2=cbDT_Nacionalidad.getItemCount();
                for(int i=0; i<indiceCbo2; i++){
                    String nombreObj2=cbDT_Nacionalidad.getItemAt(i).toString();
                    if(nombreObj2.equalsIgnoreCase(n.getPais())){
                        cbDT_Nacionalidad.setSelectedIndex(i);
                    }
                }
                
                spDT_Anos.setValue(dt.getAniosDT());
                spDT_Edad.setValue(dt.getEdad());
                
                btnCrearDT.setEnabled(false);
                btnEliminarDT.setEnabled(true);
                btnCancelarDT.setEnabled(true);
                btnActualizarDT.setEnabled(true);
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }        
    }//GEN-LAST:event_tabDTMouseReleased

    private void btnCrearDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDTActionPerformed
        DT nuevoDT=new DT();
        nuevoDT.setNombre(txtDT_Nombre.getText());
        nuevoDT.setApellido(txtDT_Apellido.getText());
        nuevoDT.setEdad(Integer.parseInt(spDT_Edad.getValue().toString()));
        nuevoDT.setAniosDT(Integer.parseInt(spDT_Anos.getValue().toString()));
        nuevoDT.setSueldoFifa(Integer.parseInt(txtDT_Sueldo.getText()));
        
        ClubDeportivo club=(ClubDeportivo)cbDT_Club.getSelectedItem();
        nuevoDT.setClubDeportivo(club.getId());
        
        Nacionalidad pais=(Nacionalidad)cbDT_Nacionalidad.getSelectedItem();
        nuevoDT.setNacionalidad(pais.getId());
        
        try {
            d.crearDT(nuevoDT);
            JOptionPane.showMessageDialog(this, "DT Creado");
            btnCancelarDT.doClick();
            cargarTablaDT(d.getDTs());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "No se ha podido crear DT: "+ex.getMessage());
        } catch (NumberFormatException exx){
            JOptionPane.showMessageDialog(this, "Existen datos invalidos");
        }
        
    }//GEN-LAST:event_btnCrearDTActionPerformed

    private void btnCancelarDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDTActionPerformed
        txtDT_Nombre.setText(null);
        txtDT_Apellido.setText(null);
        txtDT_ID.setText(null);
        txtDT_Sueldo.setText(null);
        spDT_Anos.setValue(0);
        spDT_Edad.setValue(0);
        cbDT_Club.setSelectedIndex(0);
        cbDT_Nacionalidad.setSelectedIndex(0);
        tabDT.clearSelection();        
        btnActualizarDT.setEnabled(false);
        btnCancelarDT.setEnabled(false);
        btnCrearDT.setEnabled(true);
        btnEliminarDT.setEnabled(false);        
    }//GEN-LAST:event_btnCancelarDTActionPerformed

    private void btnActualizarDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDTActionPerformed
        try {
            int id=Integer.parseInt(txtDT_ID.getText());
            String nombre=txtDT_Nombre.getText();
            String apellido=txtDT_Apellido.getText();
            int sueldo=Integer.parseInt(txtDT_Sueldo.getText());
            int edad=Integer.parseInt(spDT_Edad.getValue().toString());
            int anosDT=Integer.parseInt(spDT_Anos.getValue().toString());
            
            ClubDeportivo club=(ClubDeportivo)cbDT_Club.getSelectedItem();
            int idClub=club.getId();
            Nacionalidad pais=(Nacionalidad)cbDT_Nacionalidad.getSelectedItem();
            int idNacion=pais.getId();
            
            DT dt=new DT(id, nombre, apellido, edad, idNacion, idClub, anosDT, sueldo);
            d.actualizarDT(dt);
            cargarTablaDT(d.getDTs());
            btnCancelarDT.doClick();
            
            JOptionPane.showMessageDialog(this, "Se ha actualizado DT");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error para actualizar DT: "+ex.getMessage());
        }catch(ClassCastException e){
            JOptionPane.showMessageDialog(this, "Seleccione un valor válido");
        }
    }//GEN-LAST:event_btnActualizarDTActionPerformed

    private void btnEliminarDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDTActionPerformed
        try {
            int id=Integer.parseInt(txtDT_ID.getText());
            d.eliminarDT(id);
            cargarTablaDT(d.getDTs());
            btnCancelarDT.doClick();
            
            JOptionPane.showMessageDialog(this,"Se ha eliminado DT");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar DT: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarDTActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        try {
            String filtro=txtBusqueda.getText();
            List<DT> lista=d.buscarDTs(filtro);
            cargarTablaDT(lista);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error para buscar: "+e.getMessage());
        }
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void btnPartido_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartido_CrearActionPerformed
        Partido p;
        Object seleccionA=cboPartido_SeleccionA.getSelectedItem();
        Object seleccionB=cboPartido_SeleccionB.getSelectedItem();
        Object arbitroA=cboPartido_ArbitroA.getSelectedItem();
        Object arbitroLA=cboPartido_ArbitroLA.getSelectedItem();
        Object arbitroLB=cboPartido_ArbitroLB.getSelectedItem();
        Object arbitroD=cboPartido_ArbitroD.getSelectedItem();
        
        if(seleccionA.equals(seleccionB) 
                || arbitroA.equals(arbitroLA) 
                || arbitroA.equals(arbitroLB) 
                || arbitroA.equals(arbitroD) 
                || arbitroLA.equals(arbitroLB)
                || arbitroLA.equals(arbitroD)
                || arbitroLB.equals(arbitroD)){
            JOptionPane.showMessageDialog(this, "Existen elementos repetidos. Verifique seleccion Selecciones y Arbitros");
        }else{
            Seleccion s1=(Seleccion)seleccionA;
            Seleccion s2=(Seleccion)seleccionB;
            Arbitro aA=(Arbitro)arbitroA;
            Arbitro aLA=(Arbitro)arbitroLA;
            Arbitro aLB=(Arbitro)arbitroLB;
            Arbitro aD=(Arbitro)arbitroD;
            p=new Partido();
            p.setIdSeleccion1(s1.getId());
            p.setIdSeleccion2(s2.getId());
            p.setArbitro(aA.getId());
            p.setArbitroL1(aLA.getId());
            p.setArbitroL2(aLB.getId());
            p.setCuartoArbitro(aD.getId());
            p.setPublico((Integer)spPartido_Publico.getValue());
            p.setDia(spPartido_Dia.getValue().toString());
            p.setMes(spPartido_Mes.getValue().toString());
            p.setHoraInicio(spPartido_InicioHora.getValue().toString());
            p.setHoraTermino(spPartido_TerminoHora.getValue().toString());
            p.setMinInicio(spPartido_InicioMinuto.getValue().toString());
            p.setMinTermino(spPartido_TerminoMinuto.getValue().toString());
            Fase f=(Fase)cboPartido_Fase.getSelectedItem();
            p.setFase(f.getId());
            
            Estadio estadio=(Estadio)cboPartido_Estadio.getSelectedItem();
            p.setIdEstadio(estadio.getId());
            
            try {
                d.crearPartido(p);
                JOptionPane.showMessageDialog(this, "Partido creado");
                cargarTablaPartidos(d.getPartidos());
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al crear Partido: "+e.getMessage());
            } catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Ingrese datos validos");
            }
        }
    }//GEN-LAST:event_btnPartido_CrearActionPerformed

    private void btnPartidoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidoActualizarActionPerformed
        Partido p;
        Object seleccionA=cboPartido_SeleccionA.getSelectedItem();
        Object seleccionB=cboPartido_SeleccionB.getSelectedItem();
        Object arbitroA=cboPartido_ArbitroA.getSelectedItem();
        Object arbitroLA=cboPartido_ArbitroLA.getSelectedItem();
        Object arbitroLB=cboPartido_ArbitroLB.getSelectedItem();
        Object arbitroD=cboPartido_ArbitroD.getSelectedItem();
        
        if(seleccionA.equals(seleccionB) 
                || arbitroA.equals(arbitroLA) 
                || arbitroA.equals(arbitroLB) 
                || arbitroA.equals(arbitroD) 
                || arbitroLA.equals(arbitroLB)
                || arbitroLA.equals(arbitroD)
                || arbitroLB.equals(arbitroD)){
            JOptionPane.showMessageDialog(this, "Existen elementos repetidos. Verifique seleccion Selecciones y Arbitros");
        }else{
            Seleccion s1=(Seleccion)seleccionA;
            Seleccion s2=(Seleccion)seleccionB;
            Arbitro aA=(Arbitro)arbitroA;
            Arbitro aLA=(Arbitro)arbitroLA;
            Arbitro aLB=(Arbitro)arbitroLB;
            Arbitro aD=(Arbitro)arbitroD;
            p=new Partido();
            p.setId(Integer.parseInt(txtPartido_ID.getText()));
            p.setIdSeleccion1(s1.getId());
            p.setIdSeleccion2(s2.getId());
            p.setArbitro(aA.getId());
            p.setArbitroL1(aLA.getId());
            p.setArbitroL2(aLB.getId());
            p.setCuartoArbitro(aD.getId());
            p.setPublico((Integer)spPartido_Publico.getValue());
            p.setDia(spPartido_Dia.getValue().toString());
            p.setMes(spPartido_Mes.getValue().toString());
            p.setHoraInicio(spPartido_InicioHora.getValue().toString());
            p.setHoraTermino(spPartido_TerminoHora.getValue().toString());
            p.setMinInicio(spPartido_InicioMinuto.getValue().toString());
            p.setMinTermino(spPartido_TerminoMinuto.getValue().toString());
            Fase f=(Fase)cboPartido_Fase.getSelectedItem();
            p.setFase(f.getId());
            
            Estadio estadio=(Estadio)cboPartido_Estadio.getSelectedItem();
            p.setIdEstadio(estadio.getId());
            
            try {
                d.actualizarPartido(p);
                JOptionPane.showMessageDialog(this, "Partido actualizado");
                cargarTablaPartidos(d.getPartidos());
                btnPartidoCancelar.doClick();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar Partido: "+e.getMessage());
            } catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Ingrese datos validos");
            }
        }
    }//GEN-LAST:event_btnPartidoActualizarActionPerformed

    private void btnPartidoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidoCancelarActionPerformed
        tabPartidos.clearSelection();
        txtPartido_ID.setText(null);
        txtPartidoBusqueda.setText(null);
        cboPartido_SeleccionA.setSelectedIndex(0);
        cboPartido_SeleccionB.setSelectedIndex(0);
        cboPartido_ArbitroA.setSelectedIndex(0);
        cboPartido_ArbitroLA.setSelectedIndex(0);
        cboPartido_ArbitroLB.setSelectedIndex(0);
        cboPartido_ArbitroD.setSelectedIndex(0);
        cboPartido_Estadio.setSelectedIndex(0);
        cboPartido_Fase.setSelectedIndex(0);
        spPartido_Dia.setValue(1);
        spPartido_InicioHora.setValue(0);
        spPartido_InicioMinuto.setValue(0);
        spPartido_Mes.setValue("Enero");
        spPartido_Publico.setValue(0);
        spPartido_TerminoHora.setValue(0);
        spPartido_TerminoMinuto.setValue(0);
        
        btnPartido_Crear.setEnabled(true);
        btnPartidoEliminar.setEnabled(false);
        btnPartidoActualizar.setEnabled(false);
        btnPartidoCancelar.setEnabled(false);
    }//GEN-LAST:event_btnPartidoCancelarActionPerformed

    private void btnPartidoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidoEliminarActionPerformed
        try {
            int id=Integer.parseInt(txtPartido_ID.getText());
            d.eliminarPartido(id);
            cargarTablaPartidos(d.getPartidos());
            btnPartidoCancelar.doClick();
            JOptionPane.showMessageDialog(this, "Partido ha sido eliminado");
        } catch (SQLException ex) {
            Logger.getLogger(AppCA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPartidoEliminarActionPerformed

    private void tabPartidosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPartidosMouseReleased
        if(evt.getClickCount()==1){
            try {
                int fila=tabPartidos.getSelectedRow();
                int id=(int)tabPartidos.getValueAt(fila, 0);
                Partido p=d.getPartido(id);                
                txtPartido_ID.setText(Integer.toString(p.getId()));
                
                Seleccion s1=d.getSeleccion(p.getIdSeleccion1());
                int iCbo=cboPartido_SeleccionA.getItemCount();
                for(int i=0; i<iCbo;i++){
                    String nombreObj=cboPartido_SeleccionA.getItemAt(i).toString();
                    if(nombreObj.equalsIgnoreCase(s1.getPaisStr())){
                        cboPartido_SeleccionA.setSelectedIndex(i);
                    }
                }
                
                Seleccion s2=d.getSeleccion(p.getIdSeleccion2());
                iCbo=cboPartido_SeleccionB.getItemCount();
                for(int i=0; i<iCbo;i++){
                    String nombreObj=cboPartido_SeleccionB.getItemAt(i).toString();
                    if(nombreObj.equalsIgnoreCase(s2.getPaisStr())){
                        cboPartido_SeleccionB.setSelectedIndex(i);
                    }
                }      
                
                Arbitro a1=d.getArbitro(p.getArbitro());
                int iCboA=cboPartido_ArbitroA.getItemCount();
                for(int i=0; i<iCboA; i++){
                    String nombreObj=cboPartido_ArbitroA.getItemAt(i).toString();
                    String nombre=a1.toString();
                    if(nombreObj.equalsIgnoreCase(nombre)){
                        cboPartido_ArbitroA.setSelectedIndex(i);
                    }
                }
                
                Arbitro aL1=d.getArbitro(p.getArbitroL1());
                int iCboLA=cboPartido_ArbitroLA.getItemCount();
                for(int i=0; i<iCboLA; i++){
                    String nombreObj=cboPartido_ArbitroLA.getItemAt(i).toString();
                    String nombre=aL1.toString();
                    if(nombreObj.equalsIgnoreCase(nombre)){
                        cboPartido_ArbitroLA.setSelectedIndex(i);
                    }
                }                
                
                Arbitro aL2=d.getArbitro(p.getArbitroL2());
                int iCboLB=cboPartido_ArbitroLB.getItemCount();
                for(int i=0; i<iCboLB; i++){
                    String nombreObj=cboPartido_ArbitroLB.getItemAt(i).toString();
                    String nombre=aL2.toString();
                    if(nombreObj.equalsIgnoreCase(nombre)){
                        cboPartido_ArbitroLB.setSelectedIndex(i);
                    }
                }
                
                Arbitro a4=d.getArbitro(p.getCuartoArbitro());
                int iCboD=cboPartido_ArbitroD.getItemCount();
                for(int i=0; i<iCboD; i++){
                    String nombreObj=cboPartido_ArbitroD.getItemAt(i).toString();
                    String nombre=a4.toString();
                    if(nombreObj.equalsIgnoreCase(nombre)){
                        cboPartido_ArbitroD.setSelectedIndex(i);
                    }
                } 
                
                Estadio es=d.getEstadio(p.getIdEstadio());
                int iCboEstadio=cboPartido_Estadio.getItemCount();
                for(int i=0; i<iCboEstadio; i++){
                    String nombreObj=cboPartido_Estadio.getItemAt(i).toString();
                    String nombre=es.toString();
                    if(nombreObj.equalsIgnoreCase(nombre)){
                        cboPartido_Estadio.setSelectedIndex(i);
                    }
                }
                
                Fase f=d.getFase(p.getFase());
                int iCBOFase=cboPartido_Fase.getItemCount();
                for(int i=0; i<iCBOFase; i++){
                    String nombreObj=cboPartido_Fase.getItemAt(i).toString();
                    String nombre=f.toString();
                    if(nombreObj.equalsIgnoreCase(nombre)){
                        cboPartido_Fase.setSelectedIndex(i);
                    }
                }
                
                int mes=Integer.parseInt(p.getMes());
                String mesString=null;
                
                switch(mes){
                    case 1:
                        mesString="Enero";
                        break;
                    case 2:
                        mesString="Febrero";
                        break;
                    case 3:
                        mesString="Marzo";
                        break;
                    case 4:
                        mesString="Abril";
                        break;
                    case 5:
                        mesString="Mayo";
                        break;
                    case 6:
                        mesString="Junio";
                        break;
                    case 7:
                        mesString="Julio";
                        break;
                    case 8:
                        mesString="Agosto";
                        break;
                    case 9:
                        mesString="Septiembre";
                        break;
                    case 10:
                        mesString="Octubre";
                        break;
                    case 11:
                        mesString="Noviembre";
                        break;
                    case 12:
                        mesString="Diciembre";
                        break;
                }
                
                spPartido_Mes.setValue(mesString);
                int dia=Integer.parseInt(p.getDia());
                spPartido_Dia.setValue(dia);
                
                int h1=Integer.parseInt(p.getHoraInicio());
                spPartido_InicioHora.setValue(h1);
                int m1=Integer.parseInt(p.getMinInicio());
                spPartido_InicioMinuto.setValue(m1);
                int h2=Integer.parseInt(p.getHoraTermino());
                spPartido_TerminoHora.setValue(h2);
                int m2=Integer.parseInt(p.getMinTermino());
                spPartido_TerminoMinuto.setValue(m2);
                
                int publico=p.getPublico();
                spPartido_Publico.setValue(publico);
                
                btnPartidoActualizar.setEnabled(true);
                btnPartidoCancelar.setEnabled(true);
                btnPartidoEliminar.setEnabled(true);
                btnPartido_Crear.setEnabled(false);
                
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_tabPartidosMouseReleased

    private void txtPartidoBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPartidoBusquedaKeyReleased
        try {
            String filtro=txtPartidoBusqueda.getText();
            List<Partido> lista=d.buscarPartidos(filtro);
            cargarTablaPartidos(lista);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error para buscar: "+e.getMessage());
        }        
    }//GEN-LAST:event_txtPartidoBusquedaKeyReleased

    private void cboPosicionJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPosicionJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPosicionJugadorActionPerformed

    private void tabJugadorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabJugadorMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabJugadorMouseReleased

    private void tabJugadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabJugadorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabJugadorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        String nombre=UIManager.getSystemLookAndFeelClassName();
        try {
            UIManager.setLookAndFeel(nombre);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDT;
    private javax.swing.JButton btnActualizarJugador;
    private javax.swing.JButton btnCancelarDT;
    private javax.swing.JButton btnCancelarJugador;
    private javax.swing.JButton btnCrearDT;
    private javax.swing.JButton btnCrearJugador;
    private javax.swing.JButton btnEliminarDT;
    private javax.swing.JButton btnEliminarJugador;
    private javax.swing.JButton btnPartidoActualizar;
    private javax.swing.JButton btnPartidoCancelar;
    private javax.swing.JButton btnPartidoEliminar;
    private javax.swing.JButton btnPartido_Crear;
    private javax.swing.JComboBox<Object> cbDT_Club;
    private javax.swing.JComboBox<Object> cbDT_Nacionalidad;
    private javax.swing.JComboBox<String> cboClubDeportivoJugador;
    private javax.swing.JComboBox<String> cboEstadoFisicoJugador;
    private javax.swing.JComboBox<String> cboNacionalidadJugador;
    private javax.swing.JComboBox<Object> cboPartido_ArbitroA;
    private javax.swing.JComboBox<Object> cboPartido_ArbitroD;
    private javax.swing.JComboBox<Object> cboPartido_ArbitroLA;
    private javax.swing.JComboBox<Object> cboPartido_ArbitroLB;
    private javax.swing.JComboBox<Object> cboPartido_Estadio;
    private javax.swing.JComboBox<Object> cboPartido_Fase;
    private javax.swing.JComboBox<Object> cboPartido_SeleccionA;
    private javax.swing.JComboBox<Object> cboPartido_SeleccionB;
    private javax.swing.JComboBox<String> cboPosicionJugador;
    private javax.swing.JCheckBox chkHabilitado;
    private javax.swing.JCheckBox chkTitular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner spAtajadasJugador;
    private javax.swing.JSpinner spDT_Anos;
    private javax.swing.JSpinner spDT_Edad;
    private javax.swing.JSpinner spDebutJugador;
    private javax.swing.JSpinner spEdadJugador;
    private javax.swing.JSpinner spGolesJugador;
    private javax.swing.JSpinner spPartido_Dia;
    private javax.swing.JSpinner spPartido_InicioHora;
    private javax.swing.JSpinner spPartido_InicioMinuto;
    private javax.swing.JSpinner spPartido_Mes;
    private javax.swing.JSpinner spPartido_Publico;
    private javax.swing.JSpinner spPartido_TerminoHora;
    private javax.swing.JSpinner spPartido_TerminoMinuto;
    private javax.swing.JSpinner spSueldoJugador;
    private javax.swing.JSpinner spTarjetasAmarillas;
    private javax.swing.JSpinner spTarjetasRojas;
    private javax.swing.JTable tabDT;
    private javax.swing.JTable tabJugador;
    private javax.swing.JTable tabPartidos;
    private javax.swing.JTextField txtApellidoJugador;
    private javax.swing.JTextField txtBuscarJugador;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDT_Apellido;
    private javax.swing.JTextField txtDT_ID;
    private javax.swing.JTextField txtDT_Nombre;
    private javax.swing.JTextField txtDT_Sueldo;
    private javax.swing.JTextField txtIDJugador;
    private javax.swing.JTextField txtNombreJugador;
    private javax.swing.JTextField txtPartidoBusqueda;
    private javax.swing.JTextField txtPartido_ID;
    // End of variables declaration//GEN-END:variables

    private void iniciar() throws SQLException {
        cargarComponentesDT();
        cargarComponentesPartidos();        
    }

    private void cargarTablaPartidos(List<Partido> lista) throws SQLException{
        TMPartido modeloPartidos=new TMPartido(lista);
        tabPartidos.setModel(modeloPartidos);
    }

    private void cargarTablaDT(List<DT> dts) throws SQLException{
        TM_DT model=new TM_DT(dts);
        tabDT.setModel(model);
        tabDT.getColumnModel().getColumn(0).setPreferredWidth(5);
        tabDT.getColumnModel().getColumn(1).setPreferredWidth(10);
        tabDT.getColumnModel().getColumn(2).setPreferredWidth(10);
    }

    private void actualizarCBONacionalidad() {
        try {
            List<Nacionalidad> paises=d.getNacionalidades();
            cbDT_Nacionalidad.removeAllItems();
            
            cbDT_Nacionalidad.addItem("Seleccione Nacionalidad...");
            for(Nacionalidad n: paises){
                cbDT_Nacionalidad.addItem(n);
            }
        } catch (Exception e) {
            System.out.println("Error cargar cbGenero: "+e.getMessage());
        }
    }

    private void actualizarCBOClubDeportivo() {
        try {
            List<ClubDeportivo> clubes=d.getClubDeportivos();
            cbDT_Club.removeAllItems();
            
            cbDT_Club.addItem("Seleccione club deportivo...");
            for(ClubDeportivo club: clubes){
                cbDT_Club.addItem(club);
            }
        } catch (Exception e) {
            System.out.println("Error cargar cbDT_Club: "+e.getMessage());
        }        
    }

    private void cargarComponentesDT() throws SQLException{
        cargarTablaDT(d.getDTs());
        actualizarCBONacionalidad();
        actualizarCBOClubDeportivo();
        btnCancelarDT.doClick();        
    }

    private void cargarComponentesPartidos() throws SQLException{
        cargarTablaPartidos(d.getPartidos());
        actualizarCBOsSeleccion();
        actualizarCBOsArbitros();
        actualizarCBOsEstadio();
        actualizarCBOFases();
        btnPartidoCancelar.doClick();       
    }

    private void actualizarCBOsSeleccion() {
        try {
            List<Seleccion> selecciones=d.getSelecciones();
            cboPartido_SeleccionA.removeAllItems();
            cboPartido_SeleccionB.removeAllItems();
            
            cboPartido_SeleccionA.addItem("Seleccione seleccion...");
            for(Seleccion s: selecciones){
                cboPartido_SeleccionA.addItem(s);
            }
            
            cboPartido_SeleccionB.addItem("Seleccione seleccion...");
            for(Seleccion s: selecciones){
                cboPartido_SeleccionB.addItem(s);
            }       
                            
        } catch (Exception e) {
            System.out.println("Error cargar ComboboxSelecciones: "+e.getMessage());
        }        
    }

    private void actualizarCBOsArbitros() {
        try {
            List<Arbitro> arbitros=d.getArbitros();
            cboPartido_ArbitroA.removeAllItems();
            cboPartido_ArbitroD.removeAllItems();
            cboPartido_ArbitroLA.removeAllItems();
            cboPartido_ArbitroLB.removeAllItems();
            
            cboPartido_ArbitroA.addItem("Seleccione arbitro...");
            cboPartido_ArbitroD.addItem("Seleccione arbitro...");
            cboPartido_ArbitroLA.addItem("Seleccione arbitro...");
            cboPartido_ArbitroLB.addItem("Seleccione arbitro...");
            for(Arbitro a: arbitros){
                cboPartido_ArbitroA.addItem(a);
                cboPartido_ArbitroD.addItem(a);
                cboPartido_ArbitroLA.addItem(a);
                cboPartido_ArbitroLB.addItem(a);
            }
        } catch (Exception e) {
            System.out.println("Error cargar CBOSelecciones: "+e.getMessage());
        }          
    }

    private void actualizarCBOsEstadio() {
        try {
            List<Estadio> estadios=d.getEstadios();
            cboPartido_Estadio.removeAllItems();
            
            cboPartido_Estadio.addItem("Seleccione estadio..");
            for(Estadio e: estadios){
                cboPartido_Estadio.addItem(e);
            }
        } catch (Exception e) {
            System.out.println("Error cargar CBOestadios: "+e.getMessage());
        }          
    }

    private void actualizarCBOFases() {
        try {
            List<Fase> fases=d.getFases();
            cboPartido_Fase.removeAllItems();
            
            cboPartido_Fase.addItem("Seleccione fase..");
            for(Fase f: fases){
                cboPartido_Fase.addItem(f);
            }
        } catch (Exception e) {
            System.out.println("Error cargar CBOFases: "+e.getMessage());
        }        
    }

}
